package com.example.fake

val FakeRestaurants = listOf(
    "McDonald's",
    "Burger King",
    "KFC",
    "Subway",
    "Pizza Hut",
    "Domino's Pizza",
    "Starbucks",
    "Dunkin' Donuts",
    "Tim Hortons",
    "Dairy Queen",
    "Papa John's",
    "Wendy's",
    "Taco Bell",
    "Chipotle Mexican Grill",
    "Panera Bread",
    "Sonic Drive-In",
    "Arby's",
    "Little Caesars",
    "Popeyes Louisiana Kitchen",
    "Chick-fil-A",
    "Jimmy John's",
)
